apiVersion: v1
kind: Pod
metadata:
  name: sms-delivery-xuanwu
  labels:
    app: sms-delivery-xuanwu-label
spec:
  containers:
  - name: count
    image: busybox
    args: [/bin/sh, -c,
            'i=0; while true; do echo "$i: $(date)"; i=$((i+1)); sleep 1; done']