apiVersion: opentelemetry.io/v1alpha1
kind: Instrumentation
metadata:
  name: my-instrumentation
spec:
  exporter:
    endpoint: http://otel-collector-collector.opentelemetry:4317
  propagators:
    - tracecontext
    - baggage
    - b3
  sampler:
    type: always_on
  java:
    env: 
      - name: OTEL_EXPORTER_OTLP_ENDPOINT
        value: http://otel-collector-collector.opentelemetry:4317
  python:
    env:
      - name: OTEL_EXPORTER_OTLP_ENDPOINT
        value: http://otel-collector-collector.opentelemetry:4318
      - name: OTEL_PYTHON_LOGGING_AUTO_INSTRUMENTATION_ENABLED
        value: 'true'