apiVersion: apps/v1
kind: Deployment
metadata:
  name: petclinic
spec:
  selector:
    matchLabels:
      app: petclinic
  template:
    metadata:
      labels:
        app: petclinic
      annotations:
        instrumentation.opentelemetry.io/inject-java: "true"
    spec:
      containers:
        - image: paulczar/petclinic:2.1.0.BUILD-SNAPSHOT
          name: app
      imagePullSecrets:
      - name: default-secret