- parser:
    remove_key_name_field: true
    reserve_data: true
    parse:
      type: multi_format
      patterns:
      - format: json
        time_key: time
        time_format: %Y-%m-%dT%H:%M:%S.%NZ
      - format: regexp
        expression: /^(?<time>.+) (?<stream>stdout|stderr) [^ ]* (?<log>.*)$/
        time_format: %Y-%m-%dT%H:%M:%S.%N%:z
